name: Auto Close PRs Not Targeting Testing Branch

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  close_non_testing_pr:
    runs-on: ubuntu-latest
    if: github.base_ref != 'testing'
    steps:
      - name: Comment and Close PR
        uses: actions/github-script@v7
        with:
          script: |
            const message = `
              This pull request targets the **${{ github.base_ref }}** branch, but only PRs to the **testing** branch are allowed.

              Closing this PR automatically. Please retarget your pull request to the \`testing\` branch.

              _This action was performed automatically by a workflow._
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: message
            });
            await github.rest.pulls.update({
              ...context.repo,
              pull_number: context.issue.number,
              state: "closed"
            });
